# Generated by Django 2.1.1 on 2018-09-21 19:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='transaction_id',
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='trans_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
