# Generated by Django 2.1.1 on 2018-09-21 19:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_employee_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reference_id',
            field=models.AutoField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
