# Generated by Django 2.1.1 on 2018-09-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180921_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='d',
        ),
        migrations.AlterField(
            model_name='employee',
            name='reference_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
