# Generated by Django 2.1.1 on 2018-09-21 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20180921_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reference_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
