# Generated by Django 2.1.1 on 2018-09-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20180921_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='d',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
