# Generated by Django 2.1.1 on 2018-09-22 03:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_employee_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='address',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='d',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='trans_id',
        ),
    ]
