# Generated by Django 2.1.1 on 2018-09-22 03:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20180922_0322'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.CharField(default=0, max_length=500),
        ),
        migrations.AddField(
            model_name='employee',
            name='amount',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='employee',
            name='d',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='trans_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
