# Generated by Django 2.1.1 on 2018-09-22 03:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20180922_0331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='d',
        ),
        migrations.AddField(
            model_name='employee',
            name='reference_no',
            field=models.UUIDField(default=uuid.UUID('379495eb-8e21-4671-b11c-e2995f62ccd7')),
        ),
    ]
