# Generated by Django 2.1.1 on 2018-09-22 03:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20180922_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reference_id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reference_no',
            field=models.UUIDField(default=uuid.UUID('09fabaee-08e6-44d1-94d2-9759c04a9f12')),
        ),
    ]
