# Generated by Django 2.1.1 on 2018-09-22 03:39

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20180922_0338'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='d',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='reference_no',
            field=models.UUIDField(default=uuid.UUID('4bfa3f5b-1ce0-4fa6-8d0b-b73f73756b12')),
        ),
    ]
