# Generated by Django 2.1.1 on 2018-09-22 03:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20180922_0339'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='reference_no',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
