# Generated by Django 2.1.1 on 2018-09-22 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20180922_0342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='d',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='reference_no',
        ),
    ]
