# Generated by Django 2.1.1 on 2018-09-22 03:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_auto_20180922_0350'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='trans_no',
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
