# Generated by Django 2.1.1 on 2018-09-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_employee_trans_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
