# Generated by Django 2.1.1 on 2018-09-22 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20180922_0406'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='trans_type',
        ),
    ]
