# Generated by Django 2.1.1 on 2018-09-22 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_remove_employee_trans_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
