# Generated by Django 2.1.1 on 2018-09-22 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_employee_trans_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='trans_type',
        ),
    ]
