# Generated by Django 2.1.1 on 2018-09-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_remove_employee_trans_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
