# Generated by Django 2.1.1 on 2018-09-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_employee_trans'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='trans',
            field=models.IntegerField(default=None),
        ),
    ]
