# Generated by Django 2.1.1 on 2018-09-22 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_employee_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='status',
        ),
    ]
