# Generated by Django 2.1.1 on 2018-09-22 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0040_employee_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='trans',
            new_name='trans_type',
        ),
    ]
